modLoader="javafml"
loaderVersion="[39,)"
license="LGPLv3"
issueTrackerURL="https://github.com/slymask3/instantblocks-utility/issues"

[[mods]]
modId="instantblocks_utility"
version="0.1.0"
displayName="Instant Blocks: Utility"
updateJSONURL="https://raw.githubusercontent.com/slymask3/instant-blocks/1.19.x/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/instant-blocks"
logoFile="logo.png"
credits="Slymask3"
authors="Slymask3"
description="Generate structures or perform actions instantaneously."

[[dependencies.instantblocks_utility]]
    modId="instantblocks_core"
    mandatory=true
    versionRange="[0.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.instantblocks_utility]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.instantblocks_utility]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"